# Generated by Django 5.1 on 2024-08-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('actif', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=10)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
